POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "My First Post",
  "content": "This is the content of the post",
  "sender": "User123"
}

### קבלת כל הפוסטים
GET http://localhost:3000/posts

### קבלת פוסט לפי ID
GET http://localhost:3000/posts/678569220094f98801a77d8a

### מחיקת פוסט לפי ID
DELETE http://localhost:3000/posts/678569220094f98801a77d8a

###
GET http://localhost:3000/posts?sender=User123


### הוספת תגובה לפוסט
POST http://localhost:3000/comments/posts/678569220094f98801a77d8a
Content-Type: application/json

{
  "text": "This is a comment.",
  "userId": "456"
}

### קבלת כל התגובות
GET http://localhost:3000/comments

### קבלת כל התגובות לפוסט מסויים
GET http://localhost:3000/comments?post=678569220094f98801a77d8a

### עידכון תגובה
PUT http://localhost:3000/comments/67856b0cd6b866a4fd818e25
Content-Type: application/json

{
  "text": "Updated comment text."
}

### מחיקת תגובה
DELETE http://localhost:3000/comments/67856b0cd6b866a4fd818e25

